apiVersion: v1
kind: Secret
metadata: 
  name: wp-secrets
  namespace: apps
type: Opaque
stringData:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: CHANGE_ME_STRONG_PASSWORD
  MYSQL_ROOT_PASSWORD: CHANGE_ME_STRONG_ROOT_PASSWORD

  WP_ADMIN_USER: admin
  WP_ADMIN_PASSWORD: STRONG_PASWORD
  WP_ADMIN_EMAIL: admin@panel.com
  WP_SITE_URL: http://wp.local
  WP_SITE_TITLE: Managed WordPres