apiVersion: v1
kind: Secret
metadata: 
  name: wp-secrets
  namespace: apps
type: Opaque
stringData:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: CHANGE_ME_STRONG_PASSWORD
  MYSQL_ROOT_PASSWORD: CHANGE_ME_STRONG_ROOT_PASSWORD